### ISSUE TITLE
label CSV file workflow tracking issue

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1037]
Tracking issue for all of the items we want to fix in the label file interface in 0.13.

__Category & label name safety:__
* [x] Define what a legal label is (syntax).  AI: @sidneymbell @liaprins-czi 
* [x] Label validation implementation - UI should only accept legal labels (spec in comment below).   AI: @bkmartinjr   #1029 #970 #1056

__Annotation change logging:__
~* [ ] Logging - should we do change logging?  What is the format/spec?  AI: @sidneymbell   #988~

__Label file contents__
* [x] Implement metadata header per  #936     AI: @bkmartinjr 

__Label file naming & organization__
* [x] Finalize spec for multi-user label file naming & directory organization (back-end and front-end UI).  AI: @sidneymbell 
* [x] weak user ID implemented AI: @bkmartinjr 
* [x] backfile file change - save to directory, use timestamp not number.  AI: @bkmartinjr 
* [x] Implement revised back-end (multi-user, file names, etc).  AI: @bkmartinjr 
* [x] Implement front-end reducer & request flow.   AI: @bkmartinjr 
* [x] Implement front-end UI to capture user-specified data collection name.  AI: @colinmegill

**Comment by sidneymbell** [comment]
## Proposals
(Mostly synthesizing discussion by the team elsewhere -- for final discussion in standup on 11/15/2019)  

#### Category & label name safety:
- Legal labels contain `[a-z][A-Z][0-9][-_ ]` (including space), excluding trailing, leading or repeating spaces and tab characters 
- As suggested by Bruce, we should be generous with what we accept and stringent with what we output (i.e., validate only new category/label names as they are entered)

#### Label file contents
- Resolved (obs index and provenance header included with matching docs and easy merging with h5ad)

#### Label file naming and organization
- Organization
```
cwd/
    -> myannotations.csv
    -> annotation-backups/
           -> myannotations-TIMESTAMP.csv
              myannotations-TIMESTAMP.csv
              myannotations-TIMESTAMP.csv
              (last 10 versions)
```
- Change logs: my hypothesis is that the motivation for this log was rooted in confusion over the backup file store. I propose that we try reorganizing these as above so it is clearer, and ask for user feedback to see if this meets their usecase before adding the additional complexity of a log. If the underlying desire is for version control, there are existing solutions (e.g., github) that are much better suited for this purpose.

-  Multi-user accommodation: essentially as proposed in Bruce's wonderful document:
1 - The CLI for annotations changes to an output _directory_  
2 - On first edit, user is prompted for a filename  
3 - We store a cookie with the user-input filename + a short hash of a UUID and the input h5ad filename at the end  
4 - This string of `myannotations-27dhc979` is then used to name the output file

**Comment by bkmartinjr** [comment]
Documenting @liaprins-czi proposal for category/label names:

*Legal characters/circumstances:*
  * alpha/numeric
  * underscores
  * single space only when surrounded by other legal characters (not other space(s))

*Illegal characters/circumstances:*
  * any non-alphnumeric, non-underscore, non-space character
  * more than one space next to each other
  * leading space
  * trailing space

*Error text:*
* If the user types an illegal character (any non-alphanumeric, non-underscore, non-space character), we give them this message: `Only alphanumeric characters, underscores, and single spaces are allowed.`
* If the user types multiple spaces in a row: `Multiple consecutive spaces are not allowed.`
* If the user types a leading or a trailing space: `Leading and trailing spaces are not allowed.`
