### ISSUE TITLE
Tracking issue: annotations CLI config

### ISSUE THREAD

**Issue by sidneymbell** [chanzuckerberg/cellxgene#1066]
__For discussion. cc @liaprins-czi__

## Disable annotations flag
- [x] Swap logic of the `--annotations` flag  
Current behavior:  
`--experimental-annotations      Enable user annotation of data.  [default: False]`
Desired behavior:  
`--disable-annotations      Disable in-app annotation of data. [default: False]`  

## Naming  
- [x] Rename `--annotations-file` to `--annotations-input-file`  
- [x] Remove `experimental` from all args 

## Defaults
- [x] If no input file is specified, prompt the user for a name on startup (including their unique hash)
- [ ] If no output dir is specified, default to (1) h5ad directory if local and available; (2) cwd if not

## Misc
- [x] Make sure the docs are updated 
- [x] Update tests!

**Comment by bkmartinjr** [comment]
@sidneymbell - this looks obsolete. Can you close and/or update if my assumption is incorrect?

**Comment by sidneymbell** [comment]
@bkmartinjr -- Can you point me to which sections you think have been implemented (or just check them off :)? I think most/all of these still need to be done as we move annotations out of experimental mode.

**Comment by bkmartinjr** [comment]
Sorry, I'm not sure which are proposals, which are decisions, etc.    I was hoping this would prompt some clarifications so we could implement.

I think the "input file" and "output directory" were previously resolved, although not as suggested in this issue.

The removal of "experimental" from parameter names remains, as does the inversion of the feature flag.  But both of those are contingent on the feature stabilizing to the point we are willing to commit to it.  That is at least another major release away given the large number of UI issues outstanding.

**Comment by bmccandless** [comment]
Might be worth taking a step back and thinking about how to support annotations in a hosted environment.  As it is now, the annotations are stored in csv files on the server.   

I could imagine a feature by which annotations could be downloadable to the client, so that the user keeps possession of them (with the ability to upload them on restarts).  This would require a bit of work on the client side, and maybe some new server apis to set and get annotations.

Another option is to keep the annotations on the server side, but store the info in a database rather than csv files.  This would be useful for a cloud based hosting where local files might not be very well persisted if they are just on an elastic beanstalk instance that could go away.   Also the client might get different servers each time.

I suggest we have a command line option that specifies an annotation "mode", and then have sub options that relate to that mode.  For example, the server local file mode would take in arguments to specify the directory/file names.   A backend database mode would have options related to that accessing the database.

In a hosted environment we would also likely have to deal with user identities.

**Comment by sidneymbell** [comment]
I've updated the OP with outstanding items. @liaprins-czi would you take a look and 👍 the top post if you're OK with this?

cc @bkmartinjr

**Comment by liaprins-czi** [comment]
Looks good to me @sidneymbell Thanks!

**Comment by bkmartinjr** [comment]
thanks @sidneymbell.  Feel free to delegate some of this to me.

Two questions/concerns about the list:

> If no input file is specified, prompt the user for a name on startup (including their unique hash)

This is already implemented via the front end, and works (I just tested it).   If you have a specific bug or corner case, please add some details.

>  If no output dir is specified, default to (1) h5ad directory if local and available; (2) cwd if not

I believe this is done already - do you know it is not, or just have not checked?

**Comment by sidneymbell** [comment]
>If no input file is specified, prompt the user for a name on startup (including their unique hash)
>This is already implemented via the front end, and works (I just tested it). If you have a specific bug or corner case, please add some details.
You are correct: my mistake :)  

>If no output dir is specified, default to (1) h5ad directory if local and available; (2) cwd if not
>I believe this is done already - do you know it is not, or just have not checked?
Last I checked, we defaulted to the cwd always; I'll check again, though!

**Comment by bkmartinjr** [comment]
> > If no output dir is specified, default to (1) h5ad directory if local and available; (2) cwd if not
I believe this is done already - do you know it is not, or just have not checked?
> 
> Last I checked, we defaulted to the cwd always; I'll check again, though!

You may be right.  In many cases, we can't figure out where the data lives.

I'm actually not sure I like this default BTW - seems like it will surprise people who are used to the normal convention of writing into the local directory if no other path specified.

**Comment by sidneymbell** [comment]
That's possible, although in this case I personally think it's higher value to keep the h5ad and the annotations csv together whenever possible. I'll defer to @liaprins-czi on this one :)

**Comment by bkmartinjr** [comment]
OK.  It will overwrite if two users happen to get the same name (only likely if they both specify it on the command line, in which case, maybe it is intentional).

You two please let me know what you want :-).   In cases where it can't be derived, most likely when the dataset is specified with a web URL, we will still default to CWD.

**Comment by liaprins-czi** [comment]
I agree with @sidneymbell to keep the two files together!

**Comment by sidneymbell** [comment]
Yup, that's true either way :)

I'm working [here](https://github.com/chanzuckerberg/cellxgene/tree/sidneymbell/annotations-cli-updates). I still need to update the tests and make sure everything works. 

In the meantime, would you mind updating the output-dir default @bkmartinjr? TY!

**Comment by bkmartinjr** [comment]
> In the meantime, would you mind updating the output-dir default @bkmartinjr? TY!

sure, drop me an issue and flag it for 0.15.   I probably won't get to it until later this week
