### ISSUE TITLE
cellxgene production deployment

### ISSUE THREAD

**Issue by brianraymor** [chanzuckerberg/cellxgene#1230]
- [x] Configure application logs to go to CloudWatch Logs
- [x] Monitoring / dashboard - (CloudWatch Metrics?)
- [x] Check in with Core Infra so they know this is happening
- [x] Terraform setup for all infra
- [x] DNS name setup - _https://cellxgene.cziscience.com/_
- [x] certificate
- [x] ALB security config
- [x] enable HTTPS at load balancer
- [x] disable HTTP at load balancer (#1267)
- [x] add health check (/health) to config (#1263, #1256, chanzuckerberg/single-cell-infra#7)
- [x] export a new environment variable to the eb env:  CXG_CONFIG_FILE, which should be set to whatever CXG_DATAROOT is set to + "config.yaml".  e.g. s3://hosted-cellxgene-dev/config.yaml

In addition, please keep notes on the config, to use as source materials for @bmccandless README/tutorial on how to set this up.

**Comment by brianraymor** [comment]
Based on the issues links in the top-level summary checklist, I turned this into an epic and added the child issues.
