### ISSUE TITLE
enable diffexp for hosted

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1291]
would like to enable diffexp for hosted.  In most scenarios, this will require anti-abuse controls in the backend.  
- [x] implement a max cell set size limit for diffexp [BKM]
- [x] front-end handles this quota gracefully (warns users, doesn't show inexplicable error, etc) [BKM, Colin]  #1328
- [x] optimize/parallelize the backend [BCM]  #1327
- [x] fix NaN bug #1378
