### ISSUE TITLE
CLI MVP tracker

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#132]
This epic contains all of the tasks and other epics we want to include in the initial CLI MVP release.

---
Internal CLI UX Review:
* [ ] Jeremy: end to end test and issue logging
* [ ] Ability to test on different environments
* [ ] Update readme
* [ ] f/e: add a gene/ remove a gene
* [ ] f/e: regraph with relayout
* [ ] b/e: tracking issue
* [ ] b/e: json coding
* [ ] b/e: error handling

---

**Comment by bkmartinjr** [comment]
regraph/relayout covered by #280 and #286
