### ISSUE TITLE
Corpora schema support

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1509]
add support for importing data which conforms to the corpora schema.  Includes:
- [x] CXG encoding spec, as an accompanying doc to the corpora schema and corpora H5AD encoding specs
- [x] Update CXG spec to indicate how all Corpora fields are encoded
- [x] Update the CXG tool to follow this new encoding spec
- [x] Update cellxgene to know about this new version of CXG
- [x] Tests, as required
