### ISSUE TITLE
outage/error web page

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#1530]
When the hosted site is down, and/or a major error occurs that the front-end can't handle, we should serve a friendly page.  Need Design team input into the page and when it should be served.

Also should have alerting tied to any serving of this page so we can monitor error rates.

Suggest at least three sub-conditions serve an appropriate page:
- [ ] missing dataset / 404 - page would indicate "no such dataset" and perhaps point people back to another URL.
- [ ] outright server error / 500 class failure
- [ ] outage - load balancer served page indicating that the web tier has an outage

**Comment by brianraymor** [comment]
Closing per discussion with @maniarathi . There is only one child issue in the epic. It is closed.
