### ISSUE TITLE
Performance validation (1M+ cells) on "typical" laptop

### ISSUE THREAD

**Issue by fionagriffin** [chanzuckerberg/cellxgene#233]
Performance validation (1M+ cells) on "typical" laptop.  

Items to check/investigate:
- [x] CLI load is slow for large data.  Appears to be loading twice due to flask app.run debug flag.  Reported #351
- [x] select/deselect categorical metadata on immune_bone_marrow data set is laggy. In particular, check/uncheck louvain category values is O(500ms) due to code in Category::componentDidUpdate() and controls reducer.  PR #356
- [x] CLI fetch of expression data via /data/obs is slow.  On immune_bone_marrow data, it takes 90 seconds to load one gene (var) of data the first time.  It is memoized, so the second load is 2 seconds, but that doesn't help as we only load it once (it gets cached on the front-end).   Reported  as issue #355
- [x] For sparse data, diffexp is super slow.  Consider --dense #394
- [x] Validate correct scanpy read() options (cache, backed, etc) with benchmarking
- [x] GPU infinite loop for scatter plot, filed as #388
- [x] is CLI memoization buying much if a) anndata is in memory, and b) front-end saves universe in mem?
- [x] consider flask threading
- [x] histogram builds are very slow for large data sets (symptom: load 1.3M 10X data, hit reset button).   Partially fixed, but much more coming with Dataframe.   Fix included in PR #576
- [x] scanpy diffexp calc looks faster - benchmark and consider switching.  See #425
- [x] for expression loads (eg, add a gene, diff exp histograms), data transmission is the bottleneck, and that is primarily a matter of using JSON to transmit large numeric arrays.   Need to look at binary encoding alternatives which are both denser and cheaper to encode/decode.  #271
- [x] color-by with large number of cells is slow  #534
- [x] replace min/max in updateCellColors with the new finiteExtent() function
- [x] client-side columnar format for world/universe data would be faster than current row-major format (in  progress via Dataframe)  Fix included in PR #576
- [x] the crossfilter for universe is recreated each time world is reset to universe.   This has substantial overhead (primarily in sorting dimension indices).   The base (universe) crossfilter could be cached in universe, and just reset each time world is set to universe.  This would dramatically speed up the Reset UI function.  Fix included in PR #576
- [x] a "spatial" dimension for crossfilter could be substantially optimized if X/Y lasso selection becomes a bottleneck.   Currently it is just doing a brute force polygon containment test with a couple of small optimizations.
