### ISSUE TITLE
Tracking Issue: Cleanup tasks for REST v2 API

### ISSUE THREAD

**Issue by csweaver** [chanzuckerberg/cellxgene#257]
These are minor features that were not implemented from the REST v2 spec in the first pass for the CLI MVP.

overall
- [x] use python module for HTTP status codes
- [ ] models for params and returns
- [ ] scan internal code documentation for cell/gene and convert to obs/var
- [ ] consolidate rest documentation when get/put routes are the same/very similar
* /data
- [ ] CSV
- [ ] More tests (see PR)
- [x] fall through for accept types

// Incomplete, fill out more later

**Comment by bkmartinjr** [comment]
closing - largely obsolete at this point.
