### ISSUE TITLE
Tracking: REST 0.2 implementation cleanup

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#272]
Things we don't want to forget (in rough priority order):
* [X] Encoding gzip? (resolution: accept-encoding works, f/e will request compression)
* [x] memoization/caching in the backend (issue #282)
* [x] Need to define sort order (by index), so the f/e can remove all of the response sorting (issue #244)
* [x] Need /data/var, so the expression fetches are cleaner
* [x] error handling for bad routes / bad args on back-end
* [x] once #244 is fixed, remove manual sort from f/e (Bruce)
* [x] once #244 is fixed, update the spec

**Comment by csweaver** [comment]
Punting on the JSON float encoding -- more complicated that anticipated.

**Comment by csweaver** [comment]
Going to also punt on the uns for a single gene. Not that worth getting into the MVP
