### ISSUE TITLE
State & reducer refactoring

### ISSUE THREAD

**Issue by bkmartinjr** [chanzuckerberg/cellxgene#629]
Notes on the proposed redux state & reducer rework project.

*Goals:*
1. Add redo/undo support to app:

    * includes underlying capability to undo/redo *all* user actions (we may not
      expose all of these, but the underlying capability should support these):
        * data subset/un-subset (reset) actions (eg, world as a subset of universe)
        * selection actions, likely a subset (eg, record histogram selection, but not
          each mouse drag during selection)
        * user-defined gene add/remove, diffexp add/remove
        * plus future user features, eg, add Category/Label annotation editing
    * Ideally, implement redo/unto using a common Redux module, such as
      https://github.com/omnidan/redux-undo, described here:
      https://redux.js.org/recipes/implementing-undo-history     Using this will give
      us flexibility in the future, good documentation, and a well-tested module.
    * Connect redo/undo plumbing to an initial UI (Colin has initial UI mocks:
      https://www.figma.com/file/Y7T9LqGByddn1cKAVH16EUkU/Undo%2Fredo?node-id=0%3A1)

2. make the reducers more modular - in particular, the "controls" reducer is getting
   quite large/complex, and it would be nice if we could break it into independent
   reducers that are more in keeping with the Redux mindset.

   It is also likely that in the process of sorting out what actions are recorded
   in redo/undo history, we will need to refactor a bit.

3. Proof-of-principle action helpers suitable to enable two future use cases
   (not directly part of this project, but a good test for (1) and (2) above):
    * Remote notebook viewer: drive app remotely, eg, from a notebook plug-in, via
      RPC over a websocket (in short, RPCs sent over a websocket are transformed
      into actions, which are dispatched into the app).  Specific RPCs are TBD,
      but expected to include the equivalent of load data, reload data, and get
      current selection.
    * Headless use for taking snapshots via API.  Requirements TBD.  See issue #603

*Challenges to overcome, in order of difficulty:*

* [x] crossfilter currently is incompatible with most Redux-oriented approaches, as it is a _mutable_ data structure.   PR #647
* [x] decomposition of Controls reducer will require finding some modularity in the World/Universe data structure, but that has become much simpler with Dataframe.   PR #659
* [x] choice of redux helper (eg Redux Undo)    PR #659
* [ ] Dataframe subsets (ie, having multiple worlds on the redo stack) are not a view (subsets are a copy).   This uses a moderately large amount of memory, which means that each "world subset" in past or present history will use memory.
